### ISSUE TITLE
Failure on paginated results

### ISSUE THREAD

**Issue by jspatz** [turbot/steampipe-plugin-shopify#25]
**Describe the bug**
When a query to a Shopify table exceeds the pagination limit, the query fails with the following error:  
`ERROR:  rpc error: code = Unknown desc = status: status cannot be passed when page_info is present. See https://shopify.dev/api/usage/pagination-rest for more information.`

**Steampipe version (`steampipe -v`)**
0.20.5

**Plugin version (`steampipe plugin list`)**
0.0.1

**To reproduce**
Perform a query that reaches the Shopify API's pagination limit.  In my case, this was 250 records.  Examples:
`select * from shopify_order limit 249;`  --> works
`select * from shopify_order limit 250;` --> `ERROR:  rpc error: code = Unknown desc = status: status cannot be passed when page_info is present. See https://shopify.dev/api/usage/pagination-rest for more information.`

**Expected behavior**
On paginated response from Shopify API, the plugin follows all links to subsequent pages until they are exhausted, and returns a single dataset aggregating all pages.

**Comment by misraved** [comment]
Welcome to Steampipe @jspatz and apologies for the inconvenience.

I have raised a [PR](https://github.com/turbot/steampipe-plugin-shopify/pull/26) to fix the pagination issue 👍.

However, due to limited data, I am unable to test the fix.

Could you please build the above PR locally and test it out?

Steps to build the PR locally:
1. Clone the repo - `git clone https://github.com/turbot/steampipe-plugin-shopify.git`
2. Checkout the PR branch - `git checkout fix-pagination-shopify`
3. Run `make`
4. Test the query

Thanks once again for reporting the bug, I believe this PR should fix the pagination issue. Please let us know if you have questions 👍.

**Comment by jspatz** [comment]
@misraved Thanks for addressing my issue report.  I'm looking forward to making extensive use of Steampipe.

Unfortunately, the above PR is still not working correctly.  The commit in the branch looks like it just hardcoded a default query limit of 250 without correcting the invalid parameters being sent along with the request to query the next page.

Now, queries with paginated results are only returning _any_ output if I am using tabular output in interactive mode.  If I use psql to access the service, pass a query as a CLI argument, or set output mode to JSON, I am still getting the above error.

Secondly, even where the query executes in interactive mode, I am still only getting the now-hardcoded page limit of 250 results.  So `select * from shopify_order limit 500` returns 250 results.

My expectation would be that regardless of what value the page limit is set to, Steampipe would use a valid API call to retrieve each successive page until none are left, and then append all of the pages into a single result.

**Comment by misraved** [comment]
Apologies for the delayed response @jspatz!!

I dug into the API behavior and realized that the API `ListWithPagination` doesn't provide the option to pass the `Status` parameter as mentioned in the following section of code - 

```
	options := goshopify.OrderListOptions{
		ListOptions: goshopify.ListOptions{},
		Status:      "any",
	}
```

This blocks pagination and causes the error as you mentioned. On removing the `Status` parameter, the pagination works correctly, however, the downside to the change is the API will only list open orders, as opposed to all the orders (`open`, `closed`, and `canceled`).

I have raised an issue in the SDK repo - https://github.com/bold-commerce/go-shopify/issues/215 to make sure that we are not missing anything from our end.

Please let us know if you have questions, happy to help 👍.
